:PROPERTIES:
:ID:       cd3e6ecc-aa81-4c8c-a75a-6e98c733b16e
:END:
#+title: Error-based SQL injection
#+created: [2025-08-07 Thu 18:16]
#+filetags: :cyber:

* ERROR BASED SQL INJECTION
Error-based SQL injection refers to cases where you're able to use error messages to either extract or infer sensitive data from the database, even in blind contexts. The possibilities depend on the configuration of the database and the types of errors you're able to trigger:

You may be able to induce the application to return a specific error response based on the result of a boolean expression. You can exploit this in the same way as the conditional responses we looked at in the previous section. For more information, see Exploiting blind SQL injection by triggering conditional errors.
You may be able to trigger error messages that output the data returned by the query. This effectively turns otherwise blind SQL injection vulnerabilities into visible ones. For more information, see Extracting sensitive data via verbose SQL error messages.
** EXPLOITING BLIND SQL INJECTION BY TRIGGERING CONDITIONAL ERRORS
Some applications carry out SQL queries but their behavior doesn't change, regardless of whether the query returns any data. The technique in the previous section won't work, because injecting different boolean conditions makes no difference to the application's responses.

It's often possible to induce the application to return a different response depending on whether a SQL error occurs. You can modify the query so that it causes a database error only if the condition is true. Very often, an unhandled error thrown by the database causes some difference in the application's response, such as an error message. This enables you to infer the truth of the injected condition.

To see how this works, suppose that two requests are sent containing the following TrackingId cookie values in turn:

xyz' AND (SELECT CASE WHEN (1=2) THEN 1/0 ELSE 'a' END)='a
xyz' AND (SELECT CASE WHEN (1=1) THEN 1/0 ELSE 'a' END)='a
These inputs use the CASE keyword to test a condition and return a different expression depending on whether the expression is true:

With the first input, the CASE expression evaluates to 'a', which does not cause any error.
With the second input, it evaluates to 1/0, which causes a divide-by-zero error.
If the error causes a difference in the application's HTTP response, you can use this to determine whether the injected condition is true.

Using this technique, you can retrieve data by testing one character at a time:

xyz' AND (SELECT CASE WHEN (Username = 'Administrator' AND SUBSTRING(Password, 1, 1) > 'm') THEN 1/0 ELSE 'a' END FROM Users)='a

Note
There are different ways of triggering conditional errors, and different techniques work best on different database types. For more details, see the [[id:8e951081-f693-42af-8858-a92c9f2570b5][SQL injection cheat sheet]].
********* LABS
- solved:
  using this sql query which fails when the character in the admin password equals a,b,c, etc.
  Cookie: TrackingId=zhiBHnLA2i236B6w' AND (SELECT CASE WHEN (SELECT SUBSTR(password,1,1) FROM users WHERE username='administrator')='a' THEN TO_CHAR(1/0) ELSE 'a' END FROM dual)='a;
- password
  29g3hevhmk8n1gzfy72p
********* Note
- a CASE statement is basically an if else statement.
