:PROPERTIES:
:ID:       6427e2b6-59af-4bbc-acd7-7408b160672c
:END:
#+title: Vulnerabilities in password-based login
#+created: [2025-08-11 Mon 17:39]
#+filetags: :cyber:authentication:
* Vulnerabilities in password-based login
For websites that adopt a password-based login process, users either register for an account themselves or they are assigned an account by an administrator. This account is associated with a unique username and a secret password, which the user enters in a login form to authenticate themselves.

In this scenario, the fact that they know the secret password is taken as sufficient proof of the user's identity. This means that the security of the website is compromised if an attacker is able to either obtain or guess the login credentials of another user.

This can be achieved in a number of ways. The following sections show how an attacker can use brute-force attacks, and some of the flaws in brute-force protection. You'll also learn about the vulnerabilities in HTTP basic authentication.
- [[id:d8fce76c-ca2a-4ed1-86fa-fd537e98fe0c][Brute-force attacks]]
